# Generated by Django 5.2.3 on 2025-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalSeparatorDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Design case identifier', max_length=100)),
                ('Wg', models.FloatField(help_text='Gas mass flow rate (lb/hr)')),
                ('Wl', models.FloatField(help_text='Liquid mass flow rate (lb/hr)')),
                ('Pg', models.FloatField(help_text='Gas density (lb/ft³)')),
                ('Pl', models.FloatField(help_text='Liquid density (lb/ft³)')),
                ('Ug', models.FloatField(help_text='Gas viscosity (cP)')),
                ('dp', models.FloatField(help_text='Droplet diameter (ft)')),
                ('velocity_factor', models.FloatField(default=0.75, help_text='Velocity safety factor (typically 0.5 - 1.0)')),
                ('holdup_time', models.IntegerField(default=5, help_text='Holdup time (minutes)')),
                ('surge_factor', models.FloatField(default=1.5, help_text='Surge volume multiplier')),
                ('pressure', models.FloatField(help_text='Operating pressure (psia)')),
                ('mist_eliminator_ring', models.FloatField(default=0.5, help_text='Mist eliminator allowance (ft)')),
                ('Qg', models.FloatField(blank=True, help_text='Gas volumetric flow rate (ft³/min)', null=True)),
                ('Ql', models.FloatField(blank=True, help_text='Liquid volumetric flow rate (ft³/min)', null=True)),
                ('Cd', models.FloatField(blank=True, help_text='Drag coefficient (dimensionless)', null=True)),
                ('K', models.FloatField(blank=True, help_text='Souders-Brown K value (ft/s)', null=True)),
                ('Vt', models.FloatField(blank=True, help_text='Terminal velocity (ft/s)', null=True)),
                ('Vv', models.FloatField(blank=True, help_text='Design gas velocity (ft/s)', null=True)),
                ('Di', models.FloatField(blank=True, help_text='Internal vessel diameter (ft)', null=True)),
                ('A', models.FloatField(blank=True, help_text='Cross-sectional area (ft²)', null=True)),
                ('V_holdup', models.FloatField(blank=True, help_text='Holdup volume (ft³)', null=True)),
                ('V_surge', models.FloatField(blank=True, help_text='Surge volume (ft³)', null=True)),
                ('LLL', models.FloatField(blank=True, help_text='Low Liquid Level Height (inches)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
