# Generated by Django 5.2.3 on 2025-07-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepBox', '0002_horizontalseparatordesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='verticalseparatordesign',
            name='H_total',
            field=models.FloatField(blank=True, help_text='Total separator height (ft)', null=True),
        ),
        migrations.AddField(
            model_name='verticalseparatordesign',
            name='Hd',
            field=models.FloatField(blank=True, help_text='Disengagement height (ft)', null=True),
        ),
        migrations.AddField(
            model_name='verticalseparatordesign',
            name='Hme',
            field=models.FloatField(blank=True, help_text='Mist eliminator height (ft)', null=True),
        ),
        migrations.AddField(
            model_name='verticalseparatordesign',
            name='Holdup_Height',
            field=models.FloatField(blank=True, help_text='Height of holdup section (ft)', null=True),
        ),
        migrations.AddField(
            model_name='verticalseparatordesign',
            name='Surge_Height',
            field=models.FloatField(blank=True, help_text='Height of surge section (ft)', null=True),
        ),
        migrations.AddField(
            model_name='verticalseparatordesign',
            name='dn',
            field=models.FloatField(blank=True, help_text='Inlet nozzle diameter (ft)', null=True),
        ),
        migrations.AddField(
            model_name='verticalseparatordesign',
            name='inlet_diverter',
            field=models.BooleanField(default=False, help_text='Is an inlet diverter present?'),
        ),
        migrations.AddField(
            model_name='verticalseparatordesign',
            name='mist_eliminator_present',
            field=models.BooleanField(default=False, help_text='Is a mist eliminator installed?'),
        ),
    ]
