# Generated by Django 5.2.3 on 2025-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepBox', '0003_verticalseparatordesign_h_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verticalseparatordesign',
            name='H_lin',
            field=models.FloatField(blank=True, help_text='Height from liquid interface to nozzle centerline (ft)', null=True),
        ),
    ]
