# Generated by Django 5.2.3 on 2025-07-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepBox', '0004_verticalseparatordesign_h_lin'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='Av',
            field=models.FloatField(blank=True, help_text='Gas area above liquid (ft²)', null=True),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='D',
            field=models.FloatField(blank=True, help_text='Vessel internal diameter (ft)', null=True),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='H_liquid',
            field=models.FloatField(blank=True, help_text='Total liquid height (ft)', null=True),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='H_total',
            field=models.FloatField(blank=True, help_text='Total separator height (ft)', null=True),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='Hme',
            field=models.FloatField(blank=True, help_text='Mist eliminator height (ft)', null=True),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='Holdup_Height',
            field=models.FloatField(blank=True, help_text='Height of holdup section (ft)', null=True),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='Hv',
            field=models.FloatField(blank=True, help_text='Height of vapor space above liquid (ft)', null=True),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='Surge_Height',
            field=models.FloatField(blank=True, help_text='Height of surge section (ft)', null=True),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='mist_eliminator_present',
            field=models.BooleanField(default=False, help_text='Is a mist eliminator installed?'),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horizontalseparatordesign',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
